### ISSUE TITLE
Call _before_token_transfer in internal mint/burn of token contracts

### ISSUE THREAD

**Issue by sventime** [Supercolony-net/openbrush-contracts#69]
Would be useful to call this hook in mint/burn, e.g. to conditionally pause any balances mutation. 
We have the same in OpenZeppelin token implementations: [ERC1155::_burn](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/8dd744fc1843d285c38e54e9d439dea7f6b93495/contracts/token/ERC1155/ERC1155.sol#L326), [ERC20::_mint](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/8dd744fc1843d285c38e54e9d439dea7f6b93495/contracts/token/ERC20/ERC20.sol#L255), etc.

**Comment by xgreenx** [comment]
Done: https://github.com/Supercolony-net/openbrush-contracts/pull/73
